# Copyright (c) 2018 Michael C. Heiber
# This source file is part of the Excimontec project, which is subject to the MIT License.
# For more information, see the LICENSE file that accompanies this software.
# The Excimontec project can be found on Github at https://github.com/MikeHeiber/Excimontec
# Travis CI continuous integration build script

language: cpp
os: linux
dist: trusty
sudo: required

compiler:
    - gcc
    
env:
    - COMPILER_OPTIONS="VERSION=4.8 && MPI=mpich2"
    - COMPILER_OPTIONS="VERSION=4.8 && MPI=openmpi"
    - COMPILER_OPTIONS="VERSION=4.9 && MPI=mpich2"
    - COMPILER_OPTIONS="VERSION=4.9 && MPI=openmpi"
         
before_install:
    - eval "${COMPILER_OPTIONS}"
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq gcc-$VERSION g++-$VERSION
    - export CC=gcc-$VERSION
    - export CXX=g++-$VERSION
    - gcc --version
    - if [[ "$MPI" = mpich2 ]]; then sudo apt-get -y install -qq mpich2 libmpich2-dev; fi
    - if [[ "$MPI" = openmpi ]]; then sudo apt-get -y install -qq openmpi-bin libopenmpi-dev; fi
    - if [[ "$MPI" = mpich2 ]]; then export MPICH_CXX=g++$VERSION; fi
    - if [[ "$MPI" = openmpi ]]; then export OMPI_MPICXX=g++$VERSION; fi
    
script:
    - make
