# Copyright (c) 2018 Michael C. Heiber
# This source file is part of the Excimontec project, which is subject to the MIT License.
# For more information, see the LICENSE file that accompanies this software.
# The Excimontec project can be found on Github at https://github.com/MikeHeiber/Excimontec
# Travis CI continuous integration build script

language: cpp
os: linux
dist: trusty
sudo: required

compiler:
    - gcc
    
matrix:
    include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
      env:
         - MATRIX_EVAL="MPICH_CXX=g++-4.8"
         - MPI=mpich2
         - SHOW="-show"
         
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
      env:
         - MATRIX_EVAL="OMPI_MPICXX=g++-4.8"
         - MPI=openmpi
         - SHOW="-showme"
         
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="MPICH_CXX=g++-4.9"
         - MPI=mpich2
         - SHOW="-show"
         
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="OMPI_MPICXX=g++-4.9"
         - MPI=openmpi
         - SHOW="-showme"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="MPICH_CXX=g++-5"
         - MPI=mpich2
         - SHOW="-show"
         
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="OMPI_MPICXX=g++-5"
         - MPI=openmpi
         - SHOW="-showme"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
         - MATRIX_EVAL="MPICH_CXX=g++-6"
         - MPI=mpich2
         - SHOW="-show"
         
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
         - MATRIX_EVAL="OMPI_MPICXX=g++-6"
         - MPI=openmpi
         - SHOW="-showme"
         
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
         - MATRIX_EVAL="MPICH_CXX=g++-7"
         - MPI=mpich2
         - SHOW="-show"
         
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
         - MATRIX_EVAL="OMPI_MPICXX=g++-7"
         - MPI=openmpi
         - SHOW="-showme"
  
before_install:
    - eval "${MATRIX_EVAL}"
    - sudo apt-get update -qq
    - if [[ "$MPI" = mpich2 ]]; then sudo apt-get -y install -qq mpich2 libmpich2-dev; fi
    - if [[ "$MPI" = openmpi ]]; then sudo apt-get -y install -qq openmpi-bin libopenmpi-dev; fi
    
script:
    - make
